where is Python

diff --git a/.github/workflows/Builder.yml b/.github/workflows/Builder.yml
--- a/.github/workflows/Builder.yml
+++ b/.github/workflows/Builder.yml
@@ -111,8 +111,14 @@ jobs:
           cp -r src py4pd
           find py4pd/src -name "*.o" -type f -delete
           cp resources/README.deken.pd py4pd
+          rm py4pd/resources/BUILD.md
+          rm py4pd/resources/*.json
+          rm py4pd/resources/*.py
+          rm py4pd/resources/*.pd
+          rm py4pd/resources/*.cfg
+          rm py4pd/src/.clang-format
+          rm -r py4pd/resources/pd-lib-builder
           cp -r py4pd test
-          rm py4pd.l_amd64
 
       - name: Tests
         run: |
@@ -218,6 +224,26 @@ jobs:
         env:
           pythonName: python${{ matrix.python-version }}
         run: make PYTHON_VERSION=$pythonName extension=d_amd64
+        
+      - name: Link Python
+        env:
+          pythonName: python${{ matrix.python-version }}
+        run: |
+          python_location=$(whereis $pythonName | awk '{print $2}')
+          if [ -z "$python_location" ]; then
+            echo "Python not found."
+            exit 1
+          fi
+          target_link="/usr/local/bin/$pythonName"
+          if [ ! -e "$target_link" ]; then
+            sudo ln -s "$python_location" "$target_link"
+            echo "Symbolic link created successfully."
+          else
+            echo "File or symbolic link already exists: $target_link"
+          fi
+          ls -l "$target_link"
+          "$target_link" --version
+        
 
       - name: Copy Files and Set for Tests
         run: |
